### PR TITLE
Add warning

### PR DESCRIPTION
**Pull request by dskvr**
Don't ask how I know

### CODE REVIEW

**Comment by Mihrock1** [comment]
Hey, what does this patch do?

**Comment by Mihrock1** [comment]
I have been able to flash 319 and 312 back and forth multiple times, no bricking thankfully.

**Comment by dskvr** [comment]
Must have bad luck. Will keep trying. Was hoping removing Battery for a minute and then removing RAM, NVME and WIFI M.2 would do the trick, but still getting black screen and runaway thermals.

**Comment by dskvr** [comment]
Got it! The RAM, despite working before BIOS update, was the culprit. Later BIOS versions must have had better RAM support.

**Pull request closed without merging**
